// Koro-sensei ASCII silhouette (81×42). Source art used `$` as a background
// fill; those are stripped to spaces here so the drawing chars (`x+X:;.,&`)
// render alone against the terminal's dark background.

/* eslint-disable no-irregular-whitespace */
export const KORO_ART = [
  "                                                                                 ",
  "                                                                                 ",
  "                                    xx;:.:+                                      ",
  "                            X;                +                                  ",
  "                            +.                    +X                             ",
  "                               x             .      .X                           ",
  "                                :               .;++X                            ",
  "                                .              :                                 ",
  "                          x+XXXXX              :;                                ",
  "                       X +    XXXXXx+x+;:::;+xx +;X                              ",
  "                     ;+         XXXXXXXxxxx+xx++;.++x                            ",
  "                   .;            XXXXXXXXXXXXXX++:;xx+X                          ",
  "                 x x  & & &      XXXXXXXXXXXXXXXx;..xxx+X    XxxX X              ",
  "                : X    &  &      XXXXXXXXXXXXXXXX:: ;x+x++  .xxxx++x             ",
  "               +.XX    & &      XXXXXXXXXXXXXXXXX:.. :x+x+:x;Xxx:+x+X            ",
  "              ; XXX           XXXXXXXXXXXXXXXXXXXx .: +x+x:x:X x Xxxx+           ",
  "             X XXXXXXX     XXXXXXXXXXXXXXXXXXXXXXX+; . xx+x Xx;:++XxxxX          ",
  "             ;;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.:;;xxx+x X   :XXx++          ",
  "             :xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+x+xx+ X   x:Xxx;X         ",
  "            X:xxxxxxXXXXX::XXXXXXXXXXXXXXXXXXXXXXXXXXxx+++xx;X     XX++X         ",
  "             :xxxxxxxxXXXXXXXXXXXXXXXXXXX  xXXXXXXXXXx+++x+xx     xxXxxX         ",
  "            X:+xxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxx+++++++;     ++Xxx+         ",
  "             :+xxx xxXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxx++++++x.     XxXxxx         ",
  "             +.XXX+:;XXXXXXXXXXXXXXXXXXXXXXXXXxxxxxx+;++++++:     XxXxxX         ",
  "             X xXXXx +;xXXXXXXXXXXXXXXXXXXXXXXxxxxx+.;+++++       +XXx++         ",
  "               .xXXx+x  +Xx+xXXXXXXXXXXXXXXXXXx+;+xX;+++++:x      ;XXxx.X        ",
  "                :xXXX:  +   x   Xx+++;++++X     X  :++++x;x       ;XXxx;         ",
  "                  XXXXx++   X   ;               X++++x++:X        xXXx+x         ",
  "                  ;:XXXXX;XXX   : &  xX &  x  X:x++xxx++         .XXXx+X         ",
  "               +.    ;XXXXXXxxxx;X   +XXXxx;++xx+xxx;     X     ++XXX+xX         ",
  "            :        . ;XXXXXXXXXXXXXXXXXXxxxx+xxx+        X    +xXXxxx+         ",
  "      x:             :X+ :;+xxxxXXXxxxxxxx+xx++:.:          :X  xxxx+x+;+        ",
  "   +                 . X+;:x+::;xxxxxxx+xx;.  +++             ;X++xxxxxx+        ",
  "  x                      ++:.+xx++xxxx+:::;+++++                  ++x+x+;        ",
  "  x                       ++   x+   :;++++x x++                     ;xxx+x       ",
  "  x                   ;   x ++ + +: +xx      +                         +xX       ",
  "  x                    X +   .: ;+++        x                            ;X      ",
  "  x                    .X            +     +                               .x    ",
  "  x                    ::            .  x:;                                  :   ",
  "   XXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
  "                                                                                 ",
  "                                                                                 ",
].join("\n");
